export const FETCH_DATA_FROM_FIREBASE_START = 'FETCH_DATA_FROM_FIREBASE_START';
export const FETCH_DATA_FROM_FIREBASE_SUCCESS =
  'FETCH_DATA_FROM_FIREBASE_SUCCESS';
export const FETCH_DATA_FROM_FIREBASE_FAIL = 'FETCH_DATA_FROM_FIREBASE_FAIL';

export const FETCH_DATA_FROM_FIXER_START = 'FETCH_DATA_FROM_FIXER_START';
export const FETCH_DATA_FROM_FIXER_SUCCESS = 'FETCH_DATA_FROM_FIXER_SUCCESS';
export const FETCH_DATA_FROM_FIXER_FAIL = 'FETCH_DATA_FROM_FIXER_FAIL';
