export const FETCH_DATA_FROM_FIREBASE_START = 'FETCH_DATA_FROM_FIREBASE_START';
export const FETCH_DATA_FROM_FIREBASE_SUCCESS =
  'FETCH_DATA_FROM_FIREBASE_SUCCESS';
export const FETCH_DATA_FROM_FIREBASE_FAIL = 'FETCH_DATA_FROM_FIREBASE_FAIL';

export const FETCH_DATA_FROM_FIXER_START = 'FETCH_DATA_FROM_FIXER_START';
export const FETCH_DATA_FROM_FIXER_SUCCESS = 'FETCH_DATA_FROM_FIXER_SUCCESS';
export const FETCH_DATA_FROM_FIXER_FAIL = 'FETCH_DATA_FROM_FIXER_FAIL';

export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const UPDATE_CURRENCY_DISPLAY = 'UPDATE_CURRENCY_DISPLAY';

export const ADD_ACTIVE_CURRENCY = 'ADD_ACTIVE_CURRENCY';
export const REMOVE_ACTIVE_CURRENCY = 'REMOVE_ACTIVE_CURRENCY';
